version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'kouta'
    assignees:
      - 'kouta'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'kouta'
    assignees:
      - 'kouta'
    commit-message:
      prefix: 'ci'
      include: 'scope'
